package rules

 import java.util.Date;
 import java.text.SimpleDateFormat;
 import java.math.BigDecimal;
 import java.util.List;
 import com.alibaba.fastjson.JSON;
 import com.alibaba.fastjson.JSONObject;
 import com.alibaba.fastjson.JSONArray;
 import java.util.ArrayList;
 import com.example.hardcoredemo.modular.drools.*
 global java.util.Date now;
 global java.text.SimpleDateFormat dateFormat;
 global org.kie.api.KieBase test;

function boolean playGameOk(Hotel hotel){
    return hotel.getIfCanPackageSale();
}

query "query-1"
    $Hotels : Hotel(location == "30")
end

rule "segment_hotel"
    when
        seg : Segment( startCity in ( "XMN", "PEK", "FOC", "HGH", "TSN", "JJN" ) , cabin == "Y" )
        hotel : Hotel( ifCanPackageSale == true , location != null , location.city == seg.arriveCity, playGameOk(this) )
    then
//        drools.getRule().getName();
        System.out.println("【机+酒产品】"+seg.getProCode()+" + "+hotel.getProCode() +" + "+ playGameOk(hotel));

end

rule "segment_hotel_lounge"
    dialect "java"
    when
        seg : Segment( startCity in ( "XMN", "PEK", "FOC", "HGH", "TSN", "JJN" ) , cabin == "Y" )
        hotel : Hotel( ifCanPackageSale == true , location != null , location.city == seg.arriveCity )
        lounge:ReservedLounge(selfSupport==true,location.city == seg.startCity)
    then
    System.out.println("【机+酒+休息室产品】"+seg.getProCode()+" + "+hotel.getProCode()+" + "+lounge.getProCode());
end